name: Deploy to App Engine
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - uses: "google-github-actions/deploy-appengine@v1"
