name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to App Engine
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          deliverables: app.yaml
          working_directory: "./"
