name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to App Engine
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.1.0
        with:
          project: ${{ secrets.GCLOUD_PROJECT_ID }}
          credentials: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          deliverables: app.yaml
