name: Deploy to App Engine

on:
  push:
    branches:
      - main

permissions: read-all

env:
  CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Authentication
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy
        uses: "google-github-actions/deploy-appengine@v1"
