name: Deploy to App Engine
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "My action"
        shell: bash
        run: echo ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
