name: Deploy to App Engine
on:
  push:
    branches:
      - main

jobs:
  echo_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Secret Variable
        env:
          MY_VAL: ${{ secrets.GCLOUD_PROJECT_ID }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python
