name: Deploy to App Engine
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          working_directory: /
          deliverable: app.yaml
