name: Deploy to App Engine
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: "google-github-actions/auth@v1"
        with:
          repository: ${{ github.repository }}
      - uses: google-github-actions/auth@v1

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v1"
